### PR TITLE
Add option to delete artifacts of another repository

### PR DESCRIPTION
**Pull request by asfernandes**

### CODE REVIEW

**Comment by mknejp** [comment]
Hi and thanks for the nice work.

Just one question: how did you generate `index.js`? It's almost twice as big as if I generate it locally.

**Comment by asfernandes** [comment]
I installed latest nodejs 12 (with nvm) and ran `npm build`.

**Comment by mknejp** [comment]
I'm using node 13. Maybe that's the reason. Can you please try that and make sure you use `ncc 0.26.2`? It's a bit old, I know, I need to update everything again.

**Comment by asfernandes** [comment]
Node 13 did not make any difference in the generated file.

Updating ncc from 0.26.1 to 0.26.2 generated a different file with the same size (729313).

**Comment by asfernandes** [comment]
I also tried to build original v1 branch and the file is also much bigger than the already stored in git.

**Comment by mknejp** [comment]
Now it happens for me as well. No idea what's going on, but we're going with it.

**Comment by mknejp** [comment]
Thanks for your contribution.

**Pull request merged**
